name: Debug Secrets Configuration
on: workflow_dispatch

jobs:
  debug-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Check secret values in detail
        run: |
          echo "🔍 Debugging secret configuration..."
          
          # Check AWS_REGION
          if [ -n "${{ secrets.AWS_REGION }}" ]; then
            echo "✅ AWS_REGION exists"
            echo "AWS_REGION value: '${{ secrets.AWS_REGION }}'"
            echo "AWS_REGION length: $(echo '${{ secrets.AWS_REGION }}' | wc -c) characters"
          else
            echo "❌ AWS_REGION is empty or missing"
          fi
          
          # Check AWS_ROLE_ARN  
          if [ -n "${{ secrets.AWS_ROLE_ARN }}" ]; then
            echo "✅ AWS_ROLE_ARN exists"
            echo "AWS_ROLE_ARN starts with: $(echo '${{ secrets.AWS_ROLE_ARN }}' | cut -c1-30)..."
            echo "AWS_ROLE_ARN length: $(echo '${{ secrets.AWS_ROLE_ARN }}' | wc -c) characters"
            echo "Contains account 147997147349: $(echo '${{ secrets.AWS_ROLE_ARN }}' | grep -c '147997147349' || echo 'NO')"
          else
            echo "❌ AWS_ROLE_ARN is empty or missing"
          fi
          
          # Check for extra spaces or characters
          echo "AWS_REGION hex dump:"
          echo '${{ secrets.AWS_REGION }}' | xxd
          echo "AWS_ROLE_ARN first 50 chars hex dump:"
          echo '${{ secrets.AWS_ROLE_ARN }}' | cut -c1-50 | xxd
