name: Test Secrets Configuration
on: workflow_dispatch

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Check if secrets exist
        run: |
          echo "🔍 Testing secret availability..."
          
          if [ -n "${{ secrets.AWS_REGION }}" ]; then
            echo "✅ AWS_REGION secret is accessible"
            echo "Region: ${{ secrets.AWS_REGION }}"
          else
            echo "❌ AWS_REGION secret is missing or empty"
          fi
          
          if [ -n "${{ secrets.AWS_ROLE_ARN }}" ]; then
            echo "✅ AWS_ROLE_ARN secret is accessible" 
            echo "Role ARN length: $(echo '${{ secrets.AWS_ROLE_ARN }}' | wc -c) characters"
          else
            echo "❌ AWS_ROLE_ARN secret is missing or empty"
          fi
      
      - name: Test AWS OIDC Authentication
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: SecretTest-${{ github.run_id }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Verify AWS Connection
        run: |
          echo "🔐 Testing AWS authentication..."
          aws sts get-caller-identity
          echo "✅ Success! Your secrets are working correctly!"
